apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  Corefile: |-
    .:53 {
      {{- range $key, $middleware := .Values.middleware }}
      {{- if $middleware.enabled }}
      {{- if eq "kubernetes" $key }}
        kubernetes {{ $middleware.clusterDomain }} {
          cidrs {{ $middleware.clusterCidr }}
        }
      {{- end }}
      {{- if eq "test" $key }}
        file /etc/coredns/example.db example.org
      {{- end }}
      {{- if eq "etcd" $key }}
        etcd {{ range $middleware.zones }}{{ . }} {{ end }}{
          {{ if $middleware.path }}path {{ $middleware.path }}{{ end }}
          endpoint {{ $middleware.endpoint }}
        }
      {{- end }}
      {{- if eq "loadbalance" $key }}
        loadbalance {{ default "round_robin" $middleware.policy }}
      {{- end }}
      {{- if eq "log" $key }}
        log {{ default "stdout" $middleware.file }}
      {{- end }}
      {{- if eq "errors" $key }}
        errors 
      {{- end }}
      {{- if eq "health" $key }}
        health
      {{- end }}
      {{- if eq "prometheus" $key }}
        prometheus localhost:{{ $middleware.port }}
      {{- end }}
      {{- if eq "proxy" $key }}
        proxy . /etc/resolv.conf
      {{- end }}
      {{- if eq "cache" $key }}
        cache 30
      {{- end }}
      {{- end }}
      {{- end }}
    }
      {{- if .Values.middleware.test.enabled  }}
  example.db: |
    ; example.org test file
    example.org.            IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
    example.org.            IN      NS      b.iana-servers.net.
    example.org.            IN      NS      a.iana-servers.net.
    example.org.            IN      A       127.0.0.1
    *.example.org.          IN      A       10.0.0.10
      {{- end }}
