stages:
  # - charts
  - Artifacts
  - coredns-build-commit
  - CoreDNS

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
  - export CI_COMMIT_SHA_SHORT=$(echo ${CI_COMMIT_SHA} | cut -c -8)
  - mkdir -p ./data ; touch ./data/empty.env
  - for envfile in data/*env ; do source $envfile ; echo ----- $envfile ---- ; cat $envfile ; done

# lint:
#   stage: charts
#   script:
#     - helm lint charts/*

# publish-charts:
#   stage: charts
#   script:
#     - helm repo add charts.gitlab.io https://charts.gitlab.io/ #Add Upstream Gitlab.io for kubernetes-gitlab-demo
#     - helm lint stable/* || true
#     - for chart in stable/*; do helm dep up $chart; done
#     - mkdir -p public/stable/
#     - (cd public/stable; helm package ../../stable/*)
#     - helm repo index public/stable --url https://cncf.gitlab.io/stable
#     - helm lint demo/*
#     - for chart in demo/*; do helm dep up $chart; done
#     - mkdir -p public/demo/
#     - (cd public/demo; helm package ../../demo/*)
#     - helm repo index public/demo --url https://cncf.gitlab.io/demo
#     - find public
#   artifacts:
#     paths:
#     - public

.build_branch: &build_branch
  image: buildpack-deps:stretch
  stage: Artifacts
  variables:
    BRANCH: MUST BE SET
    ORG: MUST BE SET
    PROJECT: MUST BE SET
    PROJECT_TOKEN: MUST BE SET
    PROJECT_ID: MUST BE SET
  script:
    - apt update && apt -y install jq
    - >
      if [ -z "${BRANCH}" ]; then
        exit 0 #Should Show Skipped on Gitlab CI FIXME
      else
        echo "Checking for Latest Build"
        curl -s -L -o data/"$PROJECT".url "${BASE_URL}/${ORG}/${PROJECT}/builds/artifacts/${BRANCH}/file/release.env?job=container"
        if cat data/"$PROJECT".url | sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw ; then
        RELEASE_ENV=$(cat data/"$PROJECT".url | sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw | tail -1)
        curl -o data/"$PROJECT".env -L ${BASE_URL}/$RELEASE_ENV
        cat data/"$PROJECT".env
        else
          PROJECT_PIPELINE=$(curl -X POST -F token=$CI_JOB_TOKEN -F ref=$BRANCH https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/trigger/pipeline | jq '.id')
          # PROJECT_PIPELINE=$(curl -X POST -F token=$PROJECT_TOKEN -F ref=$BRANCH -F "variables[BUILD_TRIGGER]=yes" https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/trigger/pipeline | jq '.id')

          echo 'Wait for Build "FIX ME / HACK"'
          until [ "$JOB_STATUS" == '"success"' ]; do JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .status')" ; sleep 0.5 ; done ; echo 'Build Compleate'
          PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/$PROJECT_ID/pipelines/${PROJECT_PIPELINE}/jobs?scope=success" | jq '.[] | select(.name=="container") | .id') 
          curl -s -o data/"$PROJECT".env -L "$BASE_URL/${ORG}/${PROJECT}/-/jobs/${PROJECT_JOB}/artifacts/raw/release.env"
          cat data/"$PROJECT".env
        fi
      fi
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 5 weeks
    paths:
      - ./data

# Build-Commit:
#   image: buildpack-deps:stretch
#   stage: Artifacts
#   script:
#     - apt update && apt -y install jq
#     - echo "$COREDNS_COMMIT"
#     - >
#       if [ -z "${COREDNS_COMMIT}" ]; then
#         exit 0 #Should Show Skipped on Gitlab CI FIXME
#       else
#         echo "Checking for Container Artifact on Commit"

#         echo "Fetch Full SHA" 
#         SHA=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/repository/commits/${COREDNS_COMMIT}" | jq --raw-output '.id')
#         echo ${SHA}

#         echo "Fetch Most Recent Job ID's on Commit"
#         COMPILE_JOB=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/repository/commits/${SHA}/statuses" | jq '.[] | select(.name=="compile")' | jq -s 'sort_by(.created_at)' | jq '.[0] | .id')
#         echo ${COMPILE_JOB}
        
#         CONTAINER_JOB=$(curl --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/repository/commits/${SHA}/statuses" | jq '.[] | select(.name=="container")' | jq -s 'sort_by(.created_at)' | jq '.[0] | .id')

#         echo "Fetch Artifact"
#         curl -s -o data/coredns.env -L "$BASE_URL/coredns/coredns/-/jobs/${CONTAINER_JOB}/artifacts/raw/release.env"

#         echo "Verify Artifact"
#         if source ./data/coredns.env && env | grep COREDNS; then
#         cat data/coredns.env
#         else
#           echo "Trigger Jobs for missing Artifacts"
          
#           PROJECT_COMPILE_JOB=$(curl -X POST --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/jobs/${COMPILE_JOB}/retry" | jq '.id')
#           echo $PROJECT_COMPILE_JOB
#           echo 'Wait for Build "FIX ME / HACK"'
#           until [ "$COMPILE_JOB_STATUS" == '"success"' ]; do COMPILE_JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/jobs/${PROJECT_COMPILE_JOB}" | jq -s '.[] | .status')" ; sleep 0.5 ; done ; echo 'Build Compleate'
          
#           PROJECT_CONTAINER_JOB=$(curl -X POST --header "PRIVATE-TOKEN: ${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/jobs/${CONTAINER_JOB}/retry" | jq '.id')
#           until [ "$CONTAINER_JOB_STATUS" == '"success"' ]; do CONTAINER_JOB_STATUS="$(curl -s --header "PRIVATE-TOKEN:${TOKEN}" "https://gitlab.cncf.ci/api/v4/projects/9/jobs/${PROJECT_CONTAINER_JOB}" | jq -s '.[] | .status')" ; sleep 0.5 ; done ; echo 'Container Build Compleate'
          
#           curl -s -o data/coredns.env -L "$BASE_URL/coredns/coredns/-/jobs/${PROJECT_CONTAINER_JOB}/artifacts/raw/release.env"
#           cat data/coredns.env
#         fi
#       fi
#   artifacts:
#     name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
#     untracked: true
#     expire_in: 5 weeks
#     paths:
#       - ./data

.coredns: &coredns
  allow_failure: false
  image: registry.cncf.ci/cncf/cross-cloud/provisioning:ci-stable-v0-2-0
  stage: CoreDNS
  variables:
    KUBECONFIG: MUST BE SET
    CLOUD: MUST BE SET
  script:
    - echo "$KUBECONFIG" | base64 -d | tee ./kubeconfig
    - export KUBECONFIG=./kubeconfig
    - kubectl get nodes
    - kubectl get componentstatuses
    - env | grep COREDNS
    - helm init
    - echo Removing any previous deploys of coredns
    - helm ls --all coredns > /dev/null && helm delete --purge coredns || true
    - kubectl get svc --namespace=kube-system -l name=coredns
    - kubectl get pods --namespace=kube-system -l name=kube-dns
    - helm repo add cncf http://cncf.gitlab.io/stable
    - COREDNS_INSTALL="helm install --name coredns
         --namespace=kube-system
         --set middleware.kubernetes.clusterCidr=100.64.0.0/13
         --set middleware.prometheus.enabled=false
         --set middleware.errors.enabled=true
         --set middleware.log.enabled=true 
         --set middleware.loadbalance.enabled=false
         --set middleware.test.enabled=false
         --set image.repository=${COREDNS_IMAGE}
         --set image.tag=${COREDNS_TAG}
         cncf/coredns"
    - echo $COREDNS_INSTALL ; $COREDNS_INSTALL
    - DEPLOYED_COREDNS_IMAGE=$(kubectl get pods --namespace=kube-system -l k8s-app=coredns -o jsonpath="{.items[0].spec.containers[0].image}")
    - echo Deployed CoreDNS Image - $DEPLOYED_COREDNS_IMAGE
    - kubectl get svc --namespace=kube-system -l k8s-app=coredns
    - kubectl get pods --namespace=kube-system -l k8s-app=coredns
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 5 weeks
    paths:
      - ./data

# Cloud Deploy VARs
CoreDNS-Deploy:
  <<: *coredns
  variables:
    KUBECONFIG: "${KUBECONFIG}"
    CLOUD: "${CLOUD}"



