stages:
  - Build
  - Package

compile:
  stage: Build
  image: "ruby:2.4.1"
  script:
    - ruby -v                                   # Print out ruby version for debugging
    - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
    - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
    - bundle exec rake build
    - mv pkg/*gem .
    - echo FLUENTD_GEM=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/download >> release.env

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - "*gem"
      - "vendor"
      - Gemfile.lock
      # - release.env

container:
  stage: Package
  image: docker:latest
  script:
    - apk update && apk add git
    # - cat release.env
    # - source release.env
    # - echo $FLUENTD_GEM
    - docker build -f v0.14/debian/Dockerfile git@gitlab.staging.cncf.ci:fluent/fluentd-docker-image.git --build-arg FLUENTD_GEM=fluentd.gem
    - cat fluentd.env

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - fluentd.env
