stages:
  - Build
  - Package

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
  - export CI_COMMIT_SHA_SHORT=$(echo ${CI_COMMIT_SHA} | cut -c -8)

compile:
  stage: Build
  image: "ruby:2.4.1"
  script:
    - ruby -v                                   # Print out ruby version for debugging
    - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
    - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
    - bundle exec rake build
    - mv pkg/*gem .
    - echo FLUENTD_GEM=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/download >> release.env

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - "*gem"
      - "vendor"
      - Gemfile.lock
      # - release.env

container:
  stage: Package
  image: docker:latest
  script:
    - apk update && apk add git
    # - cat release.env
    # - source release.env
    # - echo $FLUENTD_GEM
    - export PROJECT_JOB=$(curl --header "PRIVATE-TOKEN:${TOKEN}" "${BASE_URL}/api/v4/projects/${CI_PROJECT_ID}/pipelines/${CI_PROJECT_ID}/jobs" | jq '.[] | select(.name=="compile") | .id')
    - docker build -f v0.14/debian/Dockerfile git@github.com:fluent/fluentd-docker-image.git --build-arg FLUENTD_GEM="$BASE_URL/fluent/fluentd/-/jobs/${PROJECT_JOB}/artifacts/raw/fluentd-0.14.14.gem"
    - cat fluentd.env

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - fluentd.env
