apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    k8s-app: {{ template "prometheus.name" . }}
spec:
  selector:
    k8s-app: {{ template "prometheus.name" . }}
  clusterIP: {{ .Values.clusterIP }}
  ports:
  - name: test1
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: test2
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: test3
    port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP
