# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: coredns/coredns
  tag: "006"

parallelism: 1
completions: 1

dns_service_ip: "10.0.0.10"
